const mongoose = require('mongoose');
const Pokemon = require('../models/PokemonModel'); // Adjust the path if needed

const mongoURI = 'mongodb://localhost:27017/my_database'; // Replace with your DB name

const pokemons = [
  {
    number: 3,
    name: 'Venusaur',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/3.webp',
  },
  {
    number: 4,
    name: 'Charmander',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/4.webp',
  },
  {
    number: 5,
    name: 'Charmeleon',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/5.webp',
  },
  {
    number: 6,
    name: 'Charizard',
    type: ['Fire', 'Flying'],
    imageUrl: '../static/images/Version1/6.webp',
  },
  {
    number: 7,
    name: 'Squirtle',
    type: ['Water'],
    imageUrl: '../static/images/Version1/7.webp',
  },
  {
    number: 8,
    name: 'Wartortle',
    type: ['Water'],
    imageUrl: '../static/images/Version1/8.webp',
  },
  {
    number: 9,
    name: 'Blastoise',
    type: ['Water'],
    imageUrl: '../static/images/Version1/9.webp',
  },
  {
    number: 10,
    name: 'Caterpie',
    type: ['Bug'],
    imageUrl: '../static/images/Version1/10.webp',
  },
  {
    number: 11,
    name: 'Metapod',
    type: ['Bug'],
    imageUrl: '../static/images/Version1/11.webp',
  },
  {
    number: 12,
    name: 'Butterfree',
    type: ['Bug', 'Flying'],
    imageUrl: '../static/images/Version1/12.webp',
  },
  {
    number: 13,
    name: 'Weedle',
    type: ['Bug', 'Poison'],
    imageUrl: '../static/images/Version1/13.webp',
  },
  {
    number: 14,
    name: 'Kakuna',
    type: ['Bug', 'Poison'],
    imageUrl: '../static/images/Version1/14.webp',
  },
  {
    number: 15,
    name: 'Beedrill',
    type: ['Bug', 'Poison'],
    imageUrl: '../static/images/Version1/15.webp',
  },
  {
    number: 16,
    name: 'Pidgey',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/16.webp',
  },
  {
    number: 17,
    name: 'Pidgeotto',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/17.webp',
  },
  {
    number: 18,
    name: 'Pidgeot',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/18.webp',
  },
  {
    number: 19,
    name: 'Rattata',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/19.webp',
  },
  {
    number: 20,
    name: 'Raticate',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/20.webp',
  },
  {
    number: 21,
    name: 'Spearow',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/21.webp',
  },
  {
    number: 22,
    name: 'Fearow',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/22.webp',
  },
  {
    number: 23,
    name: 'Ekans',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/23.webp',
  },
  {
    number: 24,
    name: 'Arbok',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/24.webp',
  },
  {
    number: 25,
    name: 'Pikachu',
    type: ['Electric'],
    imageUrl: '../static/images/Version1/25.webp',
  },
  {
    number: 26,
    name: 'Raichu',
    type: ['Electric'],
    imageUrl: '../static/images/Version1/26.webp',
  },
  {
    number: 27,
    name: 'Sandshrew',
    type: ['Ground'],
    imageUrl: '../static/images/Version1/27.webp',
  },
  {
    number: 28,
    name: 'Sandslash',
    type: ['Ground'],
    imageUrl: '../static/images/Version1/28.webp',
  },
  {
    number: 29,
    name: 'Nidoran♀',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/29.webp',
  },
  {
    number: 30,
    name: 'Nidorina',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/30.webp',
  },
  {
    number: 31,
    name: 'Nidoqueen',
    type: ['Poison', 'Ground'],
    imageUrl: '../static/images/Version1/31.webp',
  },
  {
    number: 32,
    name: 'Nidoran♂',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/32.webp',
  },
  {
    number: 33,
    name: 'Nidorino',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/33.webp',
  },
  {
    number: 34,
    name: 'Nidoking',
    type: ['Poison', 'Ground'],
    imageUrl: '../static/images/Version1/34.webp',
  },
  {
    number: 35,
    name: 'Clefairy',
    type: ['Fairy'],
    imageUrl: '../static/images/Version1/35.webp',
  },
  {
    number: 36,
    name: 'Clefable',
    type: ['Fairy'],
    imageUrl: '../static/images/Version1/36.webp',
  },
  {
    number: 37,
    name: 'Vulpix',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/37.webp',
  },
  {
    number: 38,
    name: 'Ninetales',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/38.webp',
  },
  {
    number: 39,
    name: 'Jigglypuff',
    type: ['Normal', 'Fairy'],
    imageUrl: '../static/images/Version1/39.webp',
  },
  {
    number: 40,
    name: 'Wigglytuff',
    type: ['Normal', 'Fairy'],
    imageUrl: '../static/images/Version1/40.webp',
  },
  {
    number: 41,
    name: 'Zubat',
    type: ['Poison', 'Flying'],
    imageUrl: '../static/images/Version1/41.webp',
  },
  {
    number: 42,
    name: 'Golbat',
    type: ['Poison', 'Flying'],
    imageUrl: '../static/images/Version1/42.webp',
  },
  {
    number: 43,
    name: 'Oddish',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/43.webp',
  },
  {
    number: 44,
    name: 'Gloom',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/44.webp',
  },
  {
    number: 45,
    name: 'Vileplume',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/45.webp',
  },
  {
    number: 46,
    name: 'Paras',
    type: ['Bug', 'Grass'],
    imageUrl: '../static/images/Version1/46.webp',
  },
  {
    number: 47,
    name: 'Parasect',
    type: ['Bug', 'Grass'],
    imageUrl: '../static/images/Version1/47.webp',
  },
  {
    number: 48,
    name: 'Venonat',
    type: ['Bug', 'Poison'],
    imageUrl: '../static/images/Version1/48.webp',
  },
  {
    number: 49,
    name: 'Venomoth',
    type: ['Bug', 'Poison'],
    imageUrl: '../static/images/Version1/49.webp',
  },
  {
    number: 50,
    name: 'Diglett',
    type: ['Ground'],
    imageUrl: '../static/images/Version1/50.webp',
  },
  {
    number: 51,
    name: 'Dugtrio',
    type: ['Ground'],
    imageUrl: '../static/images/Version1/51.webp',
  },
  {
    number: 52,
    name: 'Meowth',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/52.webp',
  },
  {
    number: 53,
    name: 'Persian',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/53.webp',
  },
  {
    number: 54,
    name: 'Psyduck',
    type: ['Water'],
    imageUrl: '../static/images/Version1/54.webp',
  },
  {
    number: 55,
    name: 'Golduck',
    type: ['Water'],
    imageUrl: '../static/images/Version1/55.webp',
  },
  {
    number: 56,
    name: 'Mankey',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/56.webp',
  },
  {
    number: 57,
    name: 'Primeape',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/57.webp',
  },
  {
    number: 58,
    name: 'Growlithe',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/58.webp',
  },
  {
    number: 59,
    name: 'Arcanine',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/59.webp',
  },
  {
    number: 60,
    name: 'Poliwag',
    type: ['Water'],
    imageUrl: '../static/images/Version1/60.webp',
  },
  {
    number: 61,
    name: 'Poliwhirl',
    type: ['Water'],
    imageUrl: '../static/images/Version1/61.webp',
  },
  {
    number: 62,
    name: 'Poliwrath',
    type: ['Water', 'Fighting'],
    imageUrl: '../static/images/Version1/62.webp',
  },
  {
    number: 63,
    name: 'Abra',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/63.webp',
  },
  {
    number: 64,
    name: 'Kadabra',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/64.webp',
  },
  {
    number: 65,
    name: 'Alakazam',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/65.webp',
  },
  {
    number: 66,
    name: 'Machop',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/66.webp',
  },
  {
    number: 67,
    name: 'Machoke',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/67.webp',
  },
  {
    number: 68,
    name: 'Machamp',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/68.webp',
  },
  {
    number: 69,
    name: 'Bellsprout',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/69.webp',
  },
  {
    number: 70,
    name: 'Weepinbell',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/70.webp',
  },
  {
    number: 71,
    name: 'Victreebel',
    type: ['Grass', 'Poison'],
    imageUrl: '../static/images/Version1/71.webp',
  },
  {
    number: 72,
    name: 'Tentacool',
    type: ['Water', 'Poison'],
    imageUrl: '../static/images/Version1/72.webp',
  },
  {
    number: 73,
    name: 'Tentacruel',
    type: ['Water', 'Poison'],
    imageUrl: '../static/images/Version1/73.webp',
  },
  {
    number: 74,
    name: 'Geodude',
    type: ['Rock', 'Ground'],
    imageUrl: '../static/images/Version1/74.webp',
  },
  {
    number: 75,
    name: 'Graveler',
    type: ['Rock', 'Ground'],
    imageUrl: '../static/images/Version1/75.webp',
  },
  {
    number: 76,
    name: 'Golem',
    type: ['Rock', 'Ground'],
    imageUrl: '../static/images/Version1/76.webp',
  },
  {
    number: 77,
    name: 'Ponyta',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/77.webp',
  },
  {
    number: 78,
    name: 'Rapidash',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/78.webp',
  },
  {
    number: 79,
    name: 'Slowpoke',
    type: ['Water', 'Psychic'],
    imageUrl: '../static/images/Version1/79.webp',
  },
  {
    number: 80,
    name: 'Slowbro',
    type: ['Water', 'Psychic'],
    imageUrl: '../static/images/Version1/80.webp',
  },
  {
    number: 81,
    name: 'Magnemite',
    type: ['Electric', 'Steel'],
    imageUrl: '../static/images/Version1/81.webp',
  },
  {
    number: 82,
    name: 'Magneton',
    type: ['Electric', 'Steel'],
    imageUrl: '../static/images/Version1/82.webp',
  },
  {
    number: 83,
    name: 'Farfetch’d',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/83.webp',
  },
  {
    number: 84,
    name: 'Doduo',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/84.webp',
  },
  {
    number: 85,
    name: 'Dodrio',
    type: ['Normal', 'Flying'],
    imageUrl: '../static/images/Version1/85.webp',
  },
  {
    number: 86,
    name: 'Seel',
    type: ['Water'],
    imageUrl: '../static/images/Version1/86.webp',
  },
  {
    number: 87,
    name: 'Dewgong',
    type: ['Water', 'Ice'],
    imageUrl: '../static/images/Version1/87.webp',
  },
  {
    number: 88,
    name: 'Grimer',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/88.webp',
  },
  {
    number: 89,
    name: 'Muk',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/89.webp',
  },
  {
    number: 90,
    name: 'Shellder',
    type: ['Water'],
    imageUrl: '../static/images/Version1/90.webp',
  },
  {
    number: 91,
    name: 'Cloyster',
    type: ['Water', 'Ice'],
    imageUrl: '../static/images/Version1/91.webp',
  },
  {
    number: 92,
    name: 'Gastly',
    type: ['Ghost', 'Poison'],
    imageUrl: '../static/images/Version1/92.webp',
  },
  {
    number: 93,
    name: 'Haunter',
    type: ['Ghost', 'Poison'],
    imageUrl: '../static/images/Version1/93.webp',
  },
  {
    number: 94,
    name: 'Gengar',
    type: ['Ghost', 'Poison'],
    imageUrl: '../static/images/Version1/94.webp',
  },
  {
    number: 95,
    name: 'Onix',
    type: ['Rock', 'Ground'],
    imageUrl: '../static/images/Version1/95.webp',
  },
  {
    number: 96,
    name: 'Drowzee',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/96.webp',
  },
  {
    number: 97,
    name: 'Hypno',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/97.webp',
  },
  {
    number: 98,
    name: 'Krabby',
    type: ['Water'],
    imageUrl: '../static/images/Version1/98.webp',
  },
  {
    number: 99,
    name: 'Kingler',
    type: ['Water'],
    imageUrl: '../static/images/Version1/99.webp',
  },
  {
    number: 100,
    name: 'Voltorb',
    type: ['Electric'],
    imageUrl: '../static/images/Version1/100.webp',
  },
  {
    number: 101,
    name: 'Electrode',
    type: ['Electric'],
    imageUrl: '../static/images/Version1/101.webp',
  },
  {
    number: 102,
    name: 'Exeggcute',
    type: ['Grass', 'Psychic'],
    imageUrl: '../static/images/Version1/102.webp',
  },
  {
    number: 103,
    name: 'Exeggutor',
    type: ['Grass', 'Psychic'],
    imageUrl: '../static/images/Version1/103.webp',
  },
  {
    number: 104,
    name: 'Cubone',
    type: ['Ground'],
    imageUrl: '../static/images/Version1/104.webp',
  },
  {
    number: 105,
    name: 'Marowak',
    type: ['Ground'],
    imageUrl: '../static/images/Version1/105.webp',
  },
  {
    number: 106,
    name: 'Hitmonlee',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/106.webp',
  },
  {
    number: 107,
    name: 'Hitmonchan',
    type: ['Fighting'],
    imageUrl: '../static/images/Version1/107.webp',
  },
  {
    number: 108,
    name: 'Lickitung',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/108.webp',
  },
  {
    number: 109,
    name: 'Koffing',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/109.webp',
  },
  {
    number: 110,
    name: 'Weezing',
    type: ['Poison'],
    imageUrl: '../static/images/Version1/110.webp',
  },
  {
    number: 111,
    name: 'Rhyhorn',
    type: ['Ground', 'Rock'],
    imageUrl: '../static/images/Version1/111.webp',
  },
  {
    number: 112,
    name: 'Rhydon',
    type: ['Ground', 'Rock'],
    imageUrl: '../static/images/Version1/112.webp',
  },
  {
    number: 113,
    name: 'Chansey',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/113.webp',
  },
  {
    number: 114,
    name: 'Tangela',
    type: ['Grass'],
    imageUrl: '../static/images/Version1/114.webp',
  },
  {
    number: 115,
    name: 'Kangaskhan',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/115.webp',
  },
  {
    number: 116,
    name: 'Horsea',
    type: ['Water'],
    imageUrl: '../static/images/Version1/116.webp',
  },
  {
    number: 117,
    name: 'Seadra',
    type: ['Water'],
    imageUrl: '../static/images/Version1/117.webp',
  },
  {
    number: 118,
    name: 'Goldeen',
    type: ['Water'],
    imageUrl: '../static/images/Version1/118.webp',
  },
  {
    number: 119,
    name: 'Seaking',
    type: ['Water'],
    imageUrl: '../static/images/Version1/119.webp',
  },
  {
    number: 120,
    name: 'Staryu',
    type: ['Water'],
    imageUrl: '../static/images/Version1/120.webp',
  },
  {
    number: 121,
    name: 'Starmie',
    type: ['Water', 'Psychic'],
    imageUrl: '../static/images/Version1/121.webp',
  },
  {
    number: 122,
    name: 'Mr. Mime',
    type: ['Psychic', 'Fairy'],
    imageUrl: '../static/images/Version1/122.webp',
  },
  {
    number: 123,
    name: 'Scyther',
    type: ['Bug', 'Flying'],
    imageUrl: '../static/images/Version1/123.webp',
  },
  {
    number: 124,
    name: 'Jynx',
    type: ['Ice', 'Psychic'],
    imageUrl: '../static/images/Version1/124.webp',
  },
  {
    number: 125,
    name: 'Electabuzz',
    type: ['Electric'],
    imageUrl: '../static/images/Version1/125.webp',
  },
  {
    number: 126,
    name: 'Magmar',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/126.webp',
  },
  {
    number: 127,
    name: 'Pinsir',
    type: ['Bug'],
    imageUrl: '../static/images/Version1/127.webp',
  },
  {
    number: 128,
    name: 'Tauros',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/128.webp',
  },
  {
    number: 129,
    name: 'Magikarp',
    type: ['Water'],
    imageUrl: '../static/images/Version1/129.webp',
  },
  {
    number: 130,
    name: 'Gyarados',
    type: ['Water', 'Flying'],
    imageUrl: '../static/images/Version1/130.webp',
  },
  {
    number: 131,
    name: 'Lapras',
    type: ['Water', 'Ice'],
    imageUrl: '../static/images/Version1/131.webp',
  },
  {
    number: 132,
    name: 'Ditto',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/132.webp',
  },
  {
    number: 133,
    name: 'Eevee',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/133.webp',
  },
  {
    number: 134,
    name: 'Vaporeon',
    type: ['Water'],
    imageUrl: '../static/images/Version1/134.webp',
  },
  {
    number: 135,
    name: 'Jolteon',
    type: ['Electric'],
    imageUrl: '../static/images/Version1/135.webp',
  },
  {
    number: 136,
    name: 'Flareon',
    type: ['Fire'],
    imageUrl: '../static/images/Version1/136.webp',
  },
  {
    number: 137,
    name: 'Porygon',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/137.webp',
  },
  {
    number: 138,
    name: 'Omanyte',
    type: ['Rock', 'Water'],
    imageUrl: '../static/images/Version1/138.webp',
  },
  {
    number: 139,
    name: 'Omastar',
    type: ['Rock', 'Water'],
    imageUrl: '../static/images/Version1/139.webp',
  },
  {
    number: 140,
    name: 'Kabuto',
    type: ['Rock', 'Water'],
    imageUrl: '../static/images/Version1/140.webp',
  },
  {
    number: 141,
    name: 'Kabutops',
    type: ['Rock', 'Water'],
    imageUrl: '../static/images/Version1/141.webp',
  },
  {
    number: 142,
    name: 'Aerodactyl',
    type: ['Rock', 'Flying'],
    imageUrl: '../static/images/Version1/142.webp',
  },
  {
    number: 143,
    name: 'Snorlax',
    type: ['Normal'],
    imageUrl: '../static/images/Version1/143.webp',
  },
  {
    number: 144,
    name: 'Articuno',
    type: ['Ice', 'Flying'],
    imageUrl: '../static/images/Version1/144.webp',
  },
  {
    number: 145,
    name: 'Zapdos',
    type: ['Electric', 'Flying'],
    imageUrl: '../static/images/Version1/145.webp',
  },
  {
    number: 146,
    name: 'Moltres',
    type: ['Fire', 'Flying'],
    imageUrl: '../static/images/Version1/146.webp',
  },
  {
    number: 147,
    name: 'Dratini',
    type: ['Dragon'],
    imageUrl: '../static/images/Version1/147.webp',
  },
  {
    number: 148,
    name: 'Dragonair',
    type: ['Dragon'],
    imageUrl: '../static/images/Version1/148.webp',
  },
  {
    number: 149,
    name: 'Dragonite',
    type: ['Dragon', 'Flying'],
    imageUrl: '../static/images/Version1/149.webp',
  },
  {
    number: 150,
    name: 'Mewtwo',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/150.webp',
  },
  {
    number: 151,
    name: 'Mew',
    type: ['Psychic'],
    imageUrl: '../static/images/Version1/151.webp',
  },
];

mongoose
  .connect(mongoURI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('MongoDB connected');

    // Wait for the connection to be fully established
    await mongoose.connection.db;

    // Check if data already exists
    const count = await Pokemon.countDocuments(); // Ensures connection is active
    if (count === 0) {
      // Insert data if collection is empty
      await Pokemon.insertMany(pokemons);
      console.log('Data seeded successfully');
    } else {
      console.log('Data already exists. Skipping seeding.');
    }

    // Disconnect after the operation
    mongoose.disconnect();
  })
  .catch((err) => {
    console.error('Error during database operation:', err);
    mongoose.disconnect();
  });
